global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/metrics'

  - job_name: 'customer'
    static_configs:
      - targets: ['customer:3000']
    metrics_path: '/metrics'

  - job_name: 'delivery'
    static_configs:
      - targets: ['delivery:3000']
    metrics_path: '/metrics'